### ISSUE TITLE
등록을 테스트 하기 위해 수정

### ISSUE THREAD

**Issue by amycandoit** [every-task/question#19]
배경

- Security 추가로 인해 글과 댓글이 등록이 안돼서 코드 수정이 필요함

기대 효과

- 로그인 되면  글과 댓글 등록이 가능하다

AC

- [ ] 코드를 수정해서 토큰을 발행 받아 글 과 댓글 등록  할 수 있도록 한다.

**Comment by taewoonglee** [comment]
테스트 완료
